LPD-39338 Apply scroll to the list of fields in form entries
liferay-bpm/liferay-portal pull request #3730
Opened 2024-10-14 21:17 UTC by igor-franca

Related [ticket](https://liferay.atlassian.net/browse/LPD-39338)

2024-10-14 21:17 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-14 21:17 UTC, igor-franca commented
ci:test:sf

2024-10-14 21:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cc585a4ca853abc04cfefa53022084b5e976464c">cc585a4ca853abc04cfefa53022084b5e976464c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPD-39338">LPD-39338</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/f1e4ca36198eb0b0f7d1c713621783a4d7cccc6a">f1e4ca36198eb0b0f7d1c713621783a4d7cccc6a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6772/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6772/jenkins-report.html">here</a>.</h5></details></html>

2024-10-14 21:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/6772/">test-portal-source-format#6772</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/6772/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3730">liferay-bpm#3730</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/40962467">[master] ci:test:sf - igor-franca &gt; liferay-bpm - PR#3730 - 2024-10-14[14:18:15]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>40962467<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/24835/">publish-testray-report#24835</a><br/></div></div>

2024-10-15 14:46 UTC, igor-franca commented
ci:test:sf

2024-10-15 14:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e6ad0e4d897e2d5317231c46841151f8d8a1b32">9e6ad0e4d897e2d5317231c46841151f8d8a1b32</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPD-39338">LPD-39338</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/823ae816eca059cb1635bccc9fd8a1c51448939b">823ae816eca059cb1635bccc9fd8a1c51448939b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6449/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6449/jenkins-report.html">here</a>.</h5></details></html>

2024-10-15 14:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6449/">test-portal-source-format#6449</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6449/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3730">liferay-bpm#3730</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/41697643">[master] ci:test:sf - igor-franca &gt; liferay-bpm - PR#3730 - 2024-10-15[07:47:06]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>41697643<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/24642/">publish-testray-report#24642</a><br/></div></div>

2024-10-16 18:23 UTC, larissacribeiro requested changes
Hey @igor-franca, it looks good to me! I discovered the reason that it was failling to me locally, I had to enable this property on my portal-ext.properties: `com.liferay.portal.kernel.upload.FileItem.threshold.size=2097152` to allow the form content size to be larger than 1 MB, in this case to 2MB, otherwise it throws an error. 
Can you check if you also have this property enabled? I think We might have to add it to our directory properties.

2024-10-16 18:23 UTC, larissacribeiro commented on modules/test/playwright/tests/dynamic-data-mapping-form-web/formEntries.spec.ts
> +	await formBuilderPage.publishButton.click();
hey @igor-franca, testing this locally, I think we don't need those two steps, considering that publishing will automatically save it, and that inside openFormSubmissionMethod() method , we are already publishing the forms as well. So this alone should cover the steps We need to achieve the form submission page, what do you think? You can test it as well and let me know!

2024-10-16 19:14 UTC, igor-franca commented
ci:test:sf

2024-10-16 19:14 UTC, igor-franca commented
ci:test:playwright

2024-10-16 19:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11429/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11429/jenkins-report.html">here</a>.</b></p>

2024-10-16 19:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6465/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6465/jenkins-report.html">here</a>.</b></p>

2024-10-16 19:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69567e36820b67a3281bafead3566e3bca54c8e3">69567e36820b67a3281bafead3566e3bca54c8e3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/igor-franca/liferay-portal/tree/LPD-39338">LPD-39338</a><br/>Branch GIT ID: <a href="https://github.com/igor-franca/liferay-portal/commit/ac3c9a4714662a4e10a2e537c08e2ae7cfe3f52b">ac3c9a4714662a4e10a2e537c08e2ae7cfe3f52b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6465/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6465/jenkins-report.html">here</a>.</h5></details></html>

2024-10-16 19:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6465/">test-portal-source-format#6465</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6465/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3730">liferay-bpm#3730</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/43733605">[master] ci:test:sf - igor-franca &gt; liferay-bpm - PR#3730 - 2024-10-16[12:14:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>43733605<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/24706/">publish-testray-report#24706</a><br/></div></div>

2024-10-16 19:32 UTC, larissacribeiro approved these changes
LGTM!! 🎉

2024-10-16 21:44 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 61 out of 86 jobs passed in 2 hours 30 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69567e36820b67a3281bafead3566e3bca54c8e3">69567e36820b67a3281bafead3566e3bca54c8e3</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/69567e36820b67a3281bafead3566e3bca54c8e3">69567e36820b67a3281bafead3566e3bca54c8e3</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/43674374">EE Development Acceptance (master) - 922 - 2024-10-16[08:38:21]</a></p><details><summary><strong>ci:test:playwright - 61 out of 86 jobs PASSED</strong></summary><div><h4>25 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11429/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>playwright-compile<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437633/">playwright-compile/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/451543/">playwright-js-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/963353/"><strike>playwright-js-tomcat90-mysql57/1/0</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/480498/">playwright-js-tomcat90-mysql57/2/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067802/">playwright-js-tomcat90-mysql57/3/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104462/">playwright-js-tomcat90-mysql57/4/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1001588/"><strike>playwright-js-tomcat90-mysql57/5/0</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007698/">playwright-js-tomcat90-mysql57/6/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005480/">playwright-js-tomcat90-mysql57/7/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437632/">playwright-js-tomcat90-mysql57/8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941695/">playwright-js-tomcat90-mysql57/9/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1001586/"><strike>playwright-js-tomcat90-mysql57/10/0</strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/371074/">playwright-js-tomcat90-mysql57/11/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1217005/">playwright-js-tomcat90-mysql57/12/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026182/"><strike>playwright-js-tomcat90-mysql57/13/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067800/">playwright-js-tomcat90-mysql57/14/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/699810/">playwright-js-tomcat90-mysql57/15/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1231652/"><strike>playwright-js-tomcat90-mysql57/16/0</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123256/">playwright-js-tomcat90-mysql57/17/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/451541/">playwright-js-tomcat90-mysql57/18/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1217004/">playwright-js-tomcat90-mysql57/19/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429514/">playwright-js-tomcat90-mysql57/20/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1001584/">playwright-js-tomcat90-mysql57/21/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941693/">playwright-js-tomcat90-mysql57/22/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763454/"><strike>playwright-js-tomcat90-mysql57/23/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763457/">playwright-js-tomcat90-mysql57/24/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941690/">playwright-js-tomcat90-mysql57/25/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005479/">playwright-js-tomcat90-mysql57/26/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941689/">playwright-js-tomcat90-mysql57/27/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123254/"><strike>playwright-js-tomcat90-mysql57/28/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941688/">playwright-js-tomcat90-mysql57/29/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383884/"><strike>playwright-js-tomcat90-mysql57/30/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067801/"><strike>playwright-js-tomcat90-mysql57/31/0</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435771/"><strike>playwright-js-tomcat90-mysql57/32/0</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026180/">playwright-js-tomcat90-mysql57/33/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/699807/">playwright-js-tomcat90-mysql57/34/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005478/"><strike>playwright-js-tomcat90-mysql57/35/0</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941694/"><strike>playwright-js-tomcat90-mysql57/36/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763456/"><strike>playwright-js-tomcat90-mysql57/37/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763458/">playwright-js-tomcat90-mysql57/38/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1116276/">playwright-js-tomcat90-mysql57/39/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1116275/">playwright-js-tomcat90-mysql57/40/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477235/">playwright-js-tomcat90-mysql57/41/0</a></li><li><a href="h [...]

2024-10-16 21:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/11429/">test-portal-acceptance-pullrequest(master)#11429</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11429/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3730">liferay-bpm#3730</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/43909176">[master] ci:test:playwright - igor-franca &gt; liferay-bpm - PR#3730 - 2024-10-16[12:14:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>43909176<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/24712/">publish-testray-report#24712</a><br/></div></div>

2024-10-17 03:06 UTC, igor-franca commented
ci:forward

2024-10-17 03:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-17 03:06 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2024-10-17 04:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11548/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11548/jenkins-report.html">here</a>.</b></p>

2024-10-17 09:32 UTC, igor-franca commented
ci:forward

2024-10-17 09:33 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-17 09:33 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2024-10-17 09:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10286/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10286/jenkins-report.html">here</a>.</b></p>

2024-10-17 10:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 26 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 34 out of 39 jobs passed in 5 hours 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c5ede076937e208feae3b423e5e5b54883a68bce">c5ede076937e208feae3b423e5e5b54883a68bce</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c5ede076937e208feae3b423e5e5b54883a68bce">c5ede076937e208feae3b423e5e5b54883a68bce</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/44233356">EE Development Acceptance (master) - 924 - 2024-10-16[21:33:13]</a></p><details><summary><strong>ci:test:stable - 26 out of 27 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477294/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763644/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067950/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435809/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005623/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375158/">js-unit/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477295/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123395/">modules-compile/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763645/">modules-compile/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005626/">modules-compile/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1217145/">modules-compile/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383927/">modules-compile/0/4</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429561/">modules-compile/0/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961518/">modules-compile/0/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477296/">modules-compile/0/7</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067952/">modules-compile/0/8</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1001744/">modules-compile/0/9</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437679/">modules-compile/0/10</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123394/">modules-compile/0/11</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/480570/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57-stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067951/">modules-integration-mysql57-stable/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1231814/">modules-integration-mysql57-stable/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123393/">modules-integration-mysql57-stable/0/2</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052896/">modules-integration-mysql57-stable/0/3</a></li></ul></li><li>modules-unit-stable<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383928/">modules-unit-stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123392/">playwright-js-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>unit-stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005625/"><strike>unit-stable/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 34 out of 39 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11548/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477294/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763644/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1067950/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/435809/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005623/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375158/">js-unit/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477295/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123395/">modules-compile/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763645/">modules-compile/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005626/">modules-compile/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1217145/">modules-compile/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/383927/">modules-compile/0/4</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/429561/">modules-compile/0/5</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961518/">modules-compile/0/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstrea [...]

2024-10-17 10:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11548/">test-portal-acceptance-pullrequest(master)#11548</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11548/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3730">liferay-bpm#3730</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/44338004">[master] ci:test:relevant - igor-franca &gt; liferay-bpm - PR#3730 - 2024-10-16[21:53:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>44338004<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/24898/">publish-testray-report#24898</a><br/></div></div>

2024-10-17 11:01 UTC, igor-franca commented
ci:report:24898

2024-10-17 11:02 UTC, liferay-continuous-integration commented
<h1>Build failed.</h1><p>Job Link: <a href="https://test-1-28.liferay.com/job/generate-testray-csv/482/">generate-testray-csv</a></p><p>The generate-testray-csv build for <b>24898</b> has failed. The testray build ID
							may not exist. Please review the build logs and contact the CI team for assistance.</p>

2024-10-17 11:16 UTC, igor-franca commented
ci:report:44338004

2024-10-17 11:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>44338004</b>.</p><p>Job Link: <a href="https://test-1-37.liferay.com/job/generate-testray-csv/396/">generate-testray-csv</a></p>

2024-10-17 11:18 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>44338004</b>.</p><p>Job Link: <a href="https://test-1-37.liferay.com/job/generate-testray-csv/396/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/396/testray-results-44338004.csv">testray-results-44338004.csv</a></p>

2024-10-17 11:27 UTC, igor-franca commented
ci:forward:force

2024-10-17 11:27 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-17 11:27 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`

2024-10-17 11:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11301/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11301/jenkins-report.html">here</a>.</b></p>

2024-10-17 11:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 26 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 34 out of 38 jobs passed in 1 hour 42 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c5ede076937e208feae3b423e5e5b54883a68bce">c5ede076937e208feae3b423e5e5b54883a68bce</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c5ede076937e208feae3b423e5e5b54883a68bce">c5ede076937e208feae3b423e5e5b54883a68bce</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/44233356">EE Development Acceptance (master) - 924 - 2024-10-16[21:33:13]</a></p><details><summary><strong>ci:test:stable - 26 out of 27 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700048/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026477/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/436001/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008078/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1068118/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007987/">js-unit/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007986/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763837/">modules-compile/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942021/">modules-compile/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1068120/">modules-compile/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1116617/">modules-compile/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232002/">modules-compile/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005750/">modules-compile/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008080/">modules-compile/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/963557/">modules-compile/0/7</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384117/">modules-compile/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008081/">modules-compile/0/9</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375340/">modules-compile/0/10</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053055/">modules-compile/0/11</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700140/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57-stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763834/">modules-integration-mysql57-stable/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008079/">modules-integration-mysql57-stable/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104820/">modules-integration-mysql57-stable/0/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/963556/">modules-integration-mysql57-stable/0/3</a></li></ul></li><li>modules-unit-stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477516/">modules-unit-stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1068117/">playwright-js-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>unit-stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763836/"><strike>unit-stable/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 34 out of 38 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10286/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700048/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026477/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/436001/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008078/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1068118/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007987/">js-unit/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1007986/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763837/">modules-compile/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942021/">modules-compile/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1068120/">modules-compile/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1116617/">modules-compile/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232002/">modules-compile/0/4</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005750/">modules-compile/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008080/">modules-compile/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pull [...]

2024-10-17 11:38 UTC, igor-franca commented
ci:forward:force

2024-10-17 11:38 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites complete:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
AND If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-17 11:38 UTC, liferay-continuous-integration commented
Skipping previously completed test suites:
- `ci:test:relevant`
- `ci:test:sf`

2024-10-17 11:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12814/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12814/jenkins-report.html">here</a>.</b></p>

2024-10-17 11:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10286/">test-portal-acceptance-pullrequest(master)#10286</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10286/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3730">liferay-bpm#3730</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/44403804">[master] ci:test:relevant - igor-franca &gt; liferay-bpm - PR#3730 - 2024-10-17[02:41:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>44403804<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/24480/">publish-testray-report#24480</a><br/></div></div>

2024-10-17 11:45 UTC, igor-franca commented
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/155260)

2024-10-17 11:45 UTC, closed without merging

2024-10-17 12:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 35 out of 35 jobs passed in 55 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/80a3903d056fbcf1c0b403362df67d9c4b8d8fb4">80a3903d056fbcf1c0b403362df67d9c4b8d8fb4</a></p><details><summary><strong>ci:test:stable - 35 out of 35 jobs PASSED</strong></summary><details><summary><strong>35 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12814/">test-portal-acceptance-pullrequest(master)</a></li><li>build-iw<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477610/">build-iw/0/0</a></li></ul></li><li>central-requirements<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005873/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123680/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961740/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008260/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477611/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232181/">functional-upgrade-tomcat90-mysql57-stable/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232180/">functional-upgrade-tomcat90-mysql57-stable/0/4</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026597/">js-unit/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763976/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053162/">modules-compile/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123681/">modules-compile/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700277/">modules-compile/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1217435/">modules-compile/0/3</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942173/">modules-compile/0/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008261/">modules-compile/0/5</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/451909/">modules-compile/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1002096/">modules-compile/0/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104989/">modules-compile/0/8</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764012/">modules-compile/0/9</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961741/">modules-compile/0/10</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/477612/">modules-compile/0/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232182/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57-stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1068269/">modules-integration-mysql57-stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1116779/">modules-integration-mysql57-stable/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053161/">modules-integration-mysql57-stable/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700276/">modules-integration-mysql57-stable/0/3</a></li></ul></li><li>modules-unit-stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005901/">modules-unit-stable/0/0</a></li></ul></li><li>playwright-compile<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/436070/">playwright-compile/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008259/">playwright-js-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>rest-builder<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1002067/">rest-builder/0/0</a></li></ul></li><li>service-builder<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005874/">service-builder/0/0</a></li></ul></li><li>unit-stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026621/">unit-stable/0/0</a></li></ul></li><li>workspaces-compile<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026598/">workspaces-compile/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12814/jenkins-report.html">here</a>.</h5></details></html>

2024-10-17 12:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12814/">test-portal-acceptance-pullrequest(master)#12814</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12814/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>stable<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3730">liferay-bpm#3730</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/44429174">[master] ci:test:stable - igor-franca &gt; liferay-bpm - PR#3730 - 2024-10-17[04:38:19]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>44429174<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28027/">publish-testray-report#28027</a><br/></div></div>

2024-10-17 13:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 35 out of 35 jobs passed in 1 hour 44 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/80a3903d056fbcf1c0b403362df67d9c4b8d8fb4">80a3903d056fbcf1c0b403362df67d9c4b8d8fb4</a></p><details><summary><strong>ci:test:stable - 35 out of 35 jobs PASSED</strong></summary><details><summary><strong>35 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/11301/">test-portal-acceptance-pullrequest(master)</a></li><li>build-iw<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942151/">build-iw/0/0</a></li></ul></li><li>central-requirements<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232138/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1068252/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005885/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1002077/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104973/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026607/">functional-upgrade-tomcat90-mysql57-stable/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1068251/">functional-upgrade-tomcat90-mysql57-stable/0/4</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961724/">js-unit/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1002061/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005887/">modules-compile/0/0</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053154/">modules-compile/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700263/">modules-compile/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005886/">modules-compile/0/3</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1053153/">modules-compile/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700262/">modules-compile/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232160/">modules-compile/0/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008245/">modules-compile/0/7</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123666/">modules-compile/0/8</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104975/">modules-compile/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1123667/">modules-compile/0/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232161/">modules-compile/0/11</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008246/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57-stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1002078/">modules-integration-mysql57-stable/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/961731/">modules-integration-mysql57-stable/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700261/">modules-integration-mysql57-stable/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942152/">modules-integration-mysql57-stable/0/3</a></li></ul></li><li>modules-unit-stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/963649/">modules-unit-stable/0/0</a></li></ul></li><li>playwright-compile<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1104974/">playwright-compile/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008244/">playwright-js-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>rest-builder<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942137/">rest-builder/0/0</a></li></ul></li><li>service-builder<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/763969/">service-builder/0/0</a></li></ul></li><li>unit-stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1116765/">unit-stable/0/0</a></li></ul></li><li>workspaces-compile<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1232139/">workspaces-compile/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11301/jenkins-report.html">here</a>.</h5></details></html>