LPD-38634 Inhibit object test to get previous value by isolating tests
liferay-bpm/liferay-portal pull request #3734
Opened 2024-10-15 13:19 UTC by rijema

Hi, y'all.

Motivation: 
[This test ](https://liferay.atlassian.net/browse/LPD-38634) was flaky in our routine affecting the suite result. I managed to reproduce the issue locally by setting a linear context where the mocked requests/responses values on BaseExportImportTestCase where instanced with the same value for all the test ( e.g: private MockLiferayResourceResponse _mockLiferayResourceResponse = new MockLiferayResourceRequest()), with that the results always were same as the CI.

![image](https://github.com/user-attachments/assets/5e857c4a-ed69-450c-944c-b73ad446d040)

Actions:
To surpass this, I'm cleaning the objects after each test, and I'm trying to isolate the execution by adding the Transaction annotation we have in other tests classes or methods (as [here](https://github.com/liferay/liferay-portal/blob/140f5d3e8bde97609a8617a008e7c8f2f52fc889/modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/testIntegration/java/com/liferay/dynamic/data/mapping/service/test/DDMStructureServiceTest.java#L251) and  For this case I'm adding all over the class, once the modified method work for other contexts as well.

2024-10-15 13:19 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-15 13:22 UTC, rijema commented
ci:test:sf

2024-10-15 13:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5960/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5960/jenkins-report.html">here</a>.</b></p>

2024-10-15 13:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e6ad0e4d897e2d5317231c46841151f8d8a1b32">9e6ad0e4d897e2d5317231c46841151f8d8a1b32</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rijema/liferay-portal/tree/LPD-38634">LPD-38634</a><br/>Branch GIT ID: <a href="https://github.com/rijema/liferay-portal/commit/4c86f7c1b5a8f55f61c0cf99ab8c8138c395560f">4c86f7c1b5a8f55f61c0cf99ab8c8138c395560f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5960/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5960/jenkins-report.html">here</a>.</h5></details></html>

2024-10-15 13:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5960/">test-portal-source-format#5960</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5960/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3734">liferay-bpm#3734</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/41634840">[master] ci:test:sf - rijema &gt; liferay-bpm - PR#3734 - 2024-10-15[06:23:38]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>41634840<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/23328/">publish-testray-report#23328</a><br/></div></div>

2024-10-15 17:51 UTC, rijema commented
As this ticket is a flaky one, related to CI (mainly the acceptance routine), I'll try to see the results from relevant/objects pointing to this test.

2024-10-15 18:44 UTC, rijema commented
ci:test:relevant

2024-10-15 18:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12792/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12792/jenkins-report.html">here</a>.</b></p>

2024-10-15 21:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 24 out of 25 jobs passed</h3><h3>:x: ci:test:relevant - 32 out of 36 jobs passed in 2 hours 33 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/920">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_12792</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/160bfa25360164cbc286b35a531ca9a90cc2f4cc">160bfa25360164cbc286b35a531ca9a90cc2f4cc</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e6ad0e4d897e2d5317231c46841151f8d8a1b32">9e6ad0e4d897e2d5317231c46841151f8d8a1b32</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/41675119">EE Development Acceptance (master) - 919 - 2024-10-15[04:38:10]</a></p><details><summary><strong>ci:test:stable - 24 out of 25 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940873/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115331/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762386/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000615/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230665/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230650/">js-unit/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762370/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940886/">modules-compile/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230667/">modules-compile/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1122462/">modules-compile/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1006741/">modules-compile/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1216210/">modules-compile/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230666/">modules-compile/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1122463/">modules-compile/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000616/">modules-compile/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000617/">modules-compile/0/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052167/">modules-compile/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1103510/">modules-compile/0/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1103511/">modules-compile/0/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762388/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57-stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1066936/">modules-integration-mysql57-stable/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940884/">modules-integration-mysql57-stable/0/1</a></li></ul></li><li>modules-unit-stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115333/">modules-unit-stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025415/">playwright-js-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>unit-stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025417/"><strike>unit-stable/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 32 out of 36 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12792/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940873/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115331/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762386/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000615/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230665/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230650/">js-unit/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762370/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940886/">modules-compile/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230667/">modules-compile/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1122462/">modules-compile/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1006741/">modules-compile/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1216210/">modules-compile/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230666/">modules-compile/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pull [...]

2024-10-15 21:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12792/">test-portal-acceptance-pullrequest(master)#12792</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12792/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3734">liferay-bpm#3734</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/42405928">[master] ci:test:relevant - rijema &gt; liferay-bpm - PR#3734 - 2024-10-15[11:44:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>42405928<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/27990/">publish-testray-report#27990</a><br/></div></div>

2024-10-16 18:55 UTC, rijema commented
ci:reevaluate:1277401_12792

2024-10-16 18:55 UTC, liferay-continuous-integration commented
CI is reevaluating the build with build ID: `1277401_12792` against the latest valid upstream results.

2024-10-16 19:09 UTC, liferay-continuous-integration commented
<html><p>Previous <code>ci:test:relevant</code><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12792">build</a> was unsuccessfully <a href="https://test-1-39.liferay.com/job/test-portal-evaluate-pullrequest/171/">reevaluated</a> against more recent upstream results.</p><h3>:x: ci:test:stable - 21 out of 22 jobs passed</h3><h3>:x: ci:test:relevant - 32 out of 36 jobs passed in 2 hours 37 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/160bfa25360164cbc286b35a531ca9a90cc2f4cc">160bfa25360164cbc286b35a531ca9a90cc2f4cc</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/160bfa25360164cbc286b35a531ca9a90cc2f4cc">160bfa25360164cbc286b35a531ca9a90cc2f4cc</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/42476813">EE Development Acceptance (master) - 920 - 2024-10-15[12:38:04]</a></p><details><summary><strong>ci:test:stable - 21 out of 22 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940873/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115331/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230650/">js-unit/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762370/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940886/">modules-compile/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230667/">modules-compile/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1122462/">modules-compile/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1006741/">modules-compile/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1216210/">modules-compile/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230666/">modules-compile/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1122463/">modules-compile/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000616/">modules-compile/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000617/">modules-compile/0/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052167/">modules-compile/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1103510/">modules-compile/0/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1103511/">modules-compile/0/11</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762388/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57-stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1066936/">modules-integration-mysql57-stable/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940884/">modules-integration-mysql57-stable/0/1</a></li></ul></li><li>modules-unit-stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115333/">modules-unit-stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025415/">playwright-js-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>unit-stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1025417/"><strike>unit-stable/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>21 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 32 out of 36 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12792"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940873/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1115331/">functional-smoke-tomcat90-mysql57-stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762386/">functional-upgrade-tomcat90-mysql57-stable/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000615/">functional-upgrade-tomcat90-mysql57-stable/0/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230665/">functional-upgrade-tomcat90-mysql57-stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230650/">js-unit/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/762370/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/940886/">modules-compile/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230667/">modules-compile/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1122462/">modules-compile/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1006741/">modules-compile/0/3</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1216210/">modules-compile/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1230666/">modules-compile/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1122463/">modules-compile/0/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000616/">modules-compile/0/7</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1000617/">modules-compile/0/8</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1052167/">modules-compile/0/9</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1103510/">modules-compile/0/10</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullreque [...]

2024-10-17 12:09 UTC, carolmariaabb requested changes

2024-10-17 12:09 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/BaseExportImportTestCase.java
> +		_mockLiferayResourceResponse = null;
My suspicious is that the [getId](https://github.com/liferay/liferay-portal/blob/80a3903d056fbcf1c0b403362df67d9c4b8d8fb4/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/BaseExportImportTestCase.java#L150) method is returning the wrong Object Folder [here](https://github.com/liferay/liferay-portal/blob/80a3903d056fbcf1c0b403362df67d9c4b8d8fb4/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/object/definitions/portlet/action/test/ObjectFolderExportImportTest.java#L147).

We are making a search by the object folder name [here](https://github.com/liferay/liferay-portal/blob/80a3903d056fbcf1c0b403362df67d9c4b8d8fb4/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/object/definitions/portlet/action/test/ObjectFolderExportImportTest.java#L245-L250).

Could you check if there is any other test that could be creating a folder with the same name? This test may be running in parallel, impacting our test.

2024-10-18 13:55 UTC, rijema commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/BaseExportImportTestCase.java
Hi. Right after mocking the request and response as setting as null.

Just my thought: Even each test is creating a instance of the objects, and if the same general test (testExportImportObjectFolder) in another environment, I was thinking if the JVM could point to an already existing object by mistake once in a while when dealing with several threads that is executing a similar queue.

2024-10-18 13:57 UTC, rijema commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/web/internal/BaseExportImportTestCase.java
> +		_mockLiferayResourceResponse = null;
Yes, there is. On SiteInitializer, the developers recently created ObjectFolders with the same names and ERC. Considering testray really relies over parallel actions, would make sense to isolate our test case using the @Transactional annotation?

2024-10-22 11:44 UTC, carolmariaabb commented
I'll close this PR for now. Let's discuss a new approach later.

2024-10-22 11:44 UTC, closed without merging