LPD-38643
liferay-bpm/liferay-portal pull request #3748
Opened 2024-10-17 14:39 UTC by icgsbr

https://liferay.atlassian.net/browse/LPD-38643

2024-10-17 14:39 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-17 14:50 UTC, icgsbr commented
ci:test:sf

2024-10-17 14:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7361/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7361/jenkins-report.html">here</a>.</b></p>

2024-10-17 14:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/24ae5874756ae6e1436657aee45bb41fd0581b3c">24ae5874756ae6e1436657aee45bb41fd0581b3c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/icgsbr/liferay-portal/tree/LPD-38643">LPD-38643</a><br/>Branch GIT ID: <a href="https://github.com/icgsbr/liferay-portal/commit/5d8d2b2b914e667e70ae595b5f599689d098aca0">5d8d2b2b914e667e70ae595b5f599689d098aca0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7361/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7361/jenkins-report.html">here</a>.</h5></details></html>

2024-10-17 14:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7361/">test-portal-source-format#7361</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7361/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3748">liferay-bpm#3748</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/44619456">[master] ci:test:sf - icgsbr &gt; liferay-bpm - PR#3748 - 2024-10-17[07:50:30]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>44619456<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28034/">publish-testray-report#28034</a><br/></div></div>

2024-10-17 14:58 UTC, icgsbr commented
ci:test:sf

2024-10-17 14:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/9181/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9181/jenkins-report.html">here</a>.</b></p>

2024-10-18 21:27 UTC, marcelabc commented
Hey @carolmariaabb 
Could you review this PR, please? :smile:

2024-10-21 11:21 UTC, carolmariaabb requested changes

2024-10-21 11:21 UTC, carolmariaabb commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectFieldLocalServiceTest.java
@icgsbr could you please simplify to `"A" + RandomTestUtil.randomString()`? Thanks!

2024-10-22 10:50 UTC, icgsbr commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectFieldLocalServiceTest.java
Hi @carolmariaabb !

According to the validation [isAllowedModifiableSystemObjectDefinitionName](https://github.com/liferay-bpm/liferay-portal/blob/24ae5874756ae6e1436657aee45bb41fd0581b3c/modules/apps/object/object-api/src/main/java/com/liferay/object/definition/util/ObjectDefinitionUtil.java#L33C2-L41C3) it must start with the string "Test". Should I change the validation?

2024-10-22 10:57 UTC, carolmariaabb approved these changes

2024-10-22 10:58 UTC, carolmariaabb commented
ci:test:forms

2024-10-22 10:58 UTC, carolmariaabb commented
ci:test:relevant

2024-10-22 10:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>forms</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11503/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11503/jenkins-report.html">here</a>.</b></p>

2024-10-22 10:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12864/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12864/jenkins-report.html">here</a>.</b></p>

2024-10-22 10:59 UTC, carolmariaabb commented
ci:stop

2024-10-22 10:59 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:forms - 0 out of 1 jobs passed in 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5ebfb76005c903916c07467d24305ab145ea91c4">5ebfb76005c903916c07467d24305ab145ea91c4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/717c6dea3af4548f74b0b0bacd3478514a081018">717c6dea3af4548f74b0b0bacd3478514a081018</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/48559993">EE Development Acceptance (master) - 938 - 2024-10-21[21:54:07]</a></p><details><summary><strong>ci:test:forms - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11503/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11503/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11503/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-10-22 11:00 UTC, carolmariaabb commented
ci:forward

2024-10-22 11:00 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-10-22 11:00 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2024-10-22 11:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10561/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10561/jenkins-report.html">here</a>.</b></p>

2024-10-22 11:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11503/">test-portal-acceptance-pullrequest(master)#11503</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11503/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>forms<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3748">liferay-bpm#3748</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/48648654">[master] ci:test:forms - icgsbr &gt; liferay-bpm - PR#3748 - 2024-10-22[03:58:16]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>48648654<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/25164/">publish-testray-report#25164</a><br/></div></div>

2024-10-22 12:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 31 out of 32 jobs passed in 1 hour 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5ebfb76005c903916c07467d24305ab145ea91c4">5ebfb76005c903916c07467d24305ab145ea91c4</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/717c6dea3af4548f74b0b0bacd3478514a081018">717c6dea3af4548f74b0b0bacd3478514a081018</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/48559993">EE Development Acceptance (master) - 938 - 2024-10-21[21:54:07]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 30 out of 32 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10561/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107974/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011029/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008525/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107985/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/767192/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1054967/">js-unit/0/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482059/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011032/">modules-compile/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1235356/">modules-compile/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1125966/">modules-compile/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1219654/">modules-compile/0/3</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008524/">modules-compile/0/4</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1070870/">modules-compile/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107984/">modules-compile/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119751/">modules-compile/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119752/">modules-compile/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011031/">modules-compile/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/767191/">modules-compile/0/10</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/944755/">modules-compile/0/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1028776/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1125964/">modules-integration-mysql57/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011030/"><strike>modules-integration-mysql57/0/1</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119750/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008523/">modules-integration-mysql57/0/3</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1070871/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008514/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1125965/">modules-unit/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1070869/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1008522/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011028/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1119749/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>30 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10561/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 717c6dea3af4548f74b0b0bacd3478514a081018:</strong></summary><ol><li><div><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011030//consoleText">modules-integration-mysql57/0/1</a><ol><li><details><summary><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011030/testReport/com.liferay.object.admin.rest.resource.v1_0.test/ObjectDefinitionResourceTest">com.liferay.object.admin.rest.resource.v1_0.test.ObjectDefinitionResourceTest</a> - <a>Failed 15 of last 18</a></summary><div><ol><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1011030//testReport/com.liferay.object.admin.rest.resource.v1_0.test/ObjectDefinitionResourceTest/testGetObjectDefinitionsPage">testGetObjectDefinitionsPage</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2024-10-22 12:13 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10561//consoleFull)

2024-10-22 12:14 UTC, closed without merging

2024-10-22 12:14 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/155456
[Console](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10561//consoleFull)

2024-10-22 12:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10561/">test-portal-acceptance-pullrequest(master)#10561</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10561/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3748">liferay-bpm#3748</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/48744084">[master] ci:test:relevant - icgsbr &gt; liferay-bpm - PR#3748 - 2024-10-22[04:00:36]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>48744084<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/23440/">publish-testray-report#23440</a><br/></div></div>