LPD-37074
liferay-bpm/liferay-portal pull request #3750
Opened 2024-10-17 17:55 UTC by vngoliveira

[LPD-37074](https://liferay.atlassian.net/browse/LPD-37074)

2024-10-17 17:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-17 17:55 UTC, vngoliveira commented
ci:test:sf

2024-10-17 17:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/6266/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6266/jenkins-report.html">here</a>.</b></p>

2024-10-17 18:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9e08765ed3881f25a6a1ca005a4af6c9fd3518a7">9e08765ed3881f25a6a1ca005a4af6c9fd3518a7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-37074-2">LPD-37074-2</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/ef3dd7b5fa7e7ab3a0d6fd0cfadf3c7b9b3c12d0">ef3dd7b5fa7e7ab3a0d6fd0cfadf3c7b9b3c12d0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6266/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6266/jenkins-report.html">here</a>.</h5></details></html>

2024-10-17 18:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/6266/">test-portal-source-format#6266</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/6266/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3750">liferay-bpm#3750</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/44984906">[master] ci:test:sf - vngoliveira &gt; liferay-bpm - PR#3750 - 2024-10-17[10:56:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>44984906<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/4107/">publish-testray-report#4107</a><br/></div></div>

2024-10-17 20:04 UTC, igor-franca requested changes
Hey @vngoliveira, Just a few details 😄

2024-10-17 20:04 UTC, igor-franca commented on modules/test/playwright/tests/dynamic-data-mapping-form-web/formSubmission.spec.ts
> +const defaultBaseUrl = liferayConfig.environment.baseUrl;
I could see that these two variables were named based on similar examples, legal 😄

2024-10-18 10:23 UTC, vngoliveira commented on modules/test/playwright/tests/dynamic-data-mapping-form-web/formSubmission.spec.ts
> +			formSubmissionPage.getByRole('option', {name: 'Algeria'})
Correct! This is one of the results displayed by the data provider.

2024-10-18 12:19 UTC, vngoliveira commented on modules/test/playwright/tests/dynamic-data-mapping-form-web/dependencies/form-with-select-field-data-provider.portlet.lar/group/20117/com.liferay.dynamic.data.mapping.model.DDMDataProviderInstance/80905.xml
Hey @igor-franca,
It wouldn't be possible because, after testing my fix in Larissa's user case, the bug continued to occur. It is only solved for my user case (a select from a list field without form rules). In a user case with form rules, as in Larissa's case, it was not solved. I need to open a ticket to fix it in the future.

2024-10-18 14:00 UTC, igor-franca commented on modules/test/playwright/tests/dynamic-data-mapping-form-web/dependencies/form-with-select-field-data-provider.portlet.lar/group/20117/com.liferay.dynamic.data.mapping.model.DDMDataProviderInstance/80905.xml
Ok, was this aligned with anyone @vngoliveira?

2024-10-22 14:16 UTC, vngoliveira commented
ci:test:sf

2024-10-22 14:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/9221/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9221/jenkins-report.html">here</a>.</b></p>

2024-10-22 14:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/20c16b763e47400f6e4d7cc1f462a054278d1d4b">20c16b763e47400f6e4d7cc1f462a054278d1d4b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-37074-2">LPD-37074-2</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/93cd1301a71f83db99ea7ab714ca8a04dd2bf86b">93cd1301a71f83db99ea7ab714ca8a04dd2bf86b</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/9221/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9221/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/test/playwright/tests/dynamic-data-mapping-form-web/env/portal-ext.properties expected:&lt;...eshold.size=2097152
     [java] [
     [java] ]database.partition.e...&gt; but was:&lt;...eshold.size=2097152
     [java] []database.partition.e...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 1:46.839 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-32/job/test-portal-source-format/9221//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20241022072023149.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20241022072023149.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1827179210.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1144324045
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 144ms
[junitreport] Deleting: /tmp/null1144324045
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 10-22-2024 07:20:26:543 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2024-10-22 14:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/9221/">test-portal-source-format#9221</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9221/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3750">liferay-bpm#3750</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/48865225">[master] ci:test:sf - vngoliveira &gt; liferay-bpm - PR#3750 - 2024-10-22[07:17:04]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>48865225<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/34712/">publish-testray-report#34712</a><br/></div></div>

2024-10-22 14:39 UTC, carolmariaabb approved these changes
LGTM!

2024-10-22 14:40 UTC, vngoliveira commented on modules/test/playwright/tests/dynamic-data-mapping-form-web/env/portal-ext.properties
> +database.partition.enabled=true
Hey @igor-franca,
This change is made by the afcb command

2024-10-22 14:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/7540/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7540/jenkins-report.html">here</a>.</b></p>

2024-10-22 14:46 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/20c16b763e47400f6e4d7cc1f462a054278d1d4b">20c16b763e47400f6e4d7cc1f462a054278d1d4b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-37074-2">LPD-37074-2</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/9389a9a85dfe4096ea389be7f189f252082dc98d">9389a9a85dfe4096ea389be7f189f252082dc98d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7540/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7540/jenkins-report.html">here</a>.</h5></details></html>

2024-10-23 17:52 UTC, igor-franca commented
We've made some improvements to testing in person. Waiting for the force push with the latest changes 😄

2024-10-23 17:59 UTC, vngoliveira commented
ci:test:sf

2024-10-23 18:00 UTC, vngoliveira commented
ci:test:relevant

2024-10-23 18:00 UTC, vngoliveira commented
ci:test:playwright

2024-10-23 18:00 UTC, vngoliveira commented
ci:test:forms

2024-10-23 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11623/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11623/jenkins-report.html">here</a>.</b></p>

2024-10-23 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>playwright</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11526/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11526/jenkins-report.html">here</a>.</b></p>

2024-10-23 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6523/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6523/jenkins-report.html">here</a>.</b></p>

2024-10-23 18:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>forms</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12877/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12877/jenkins-report.html">here</a>.</b></p>

2024-10-23 18:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/449fa8fd0fbf5b9bbae254fdd8b549332370371e">449fa8fd0fbf5b9bbae254fdd8b549332370371e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-37074-2">LPD-37074-2</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/0665ad100409e614edb042d86ccf1aa6f6f4a114">0665ad100409e614edb042d86ccf1aa6f6f4a114</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6523/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6523/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts check:ci
     [exec] 
     [exec] ⚙️ Running preflight checks...
     [exec] 
     [exec] ⚙️ Checking outdated tsconfig.json files ...
     [exec] 
     [exec] ⚙️ Running TypeScript checks on modified files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] 
     [exec] ⚙️ Running format checks on modified files...
     [exec]    /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/dynamic-data-mapping-form-web/formSubmission.spec.ts
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec]      1:1  error  File has format errors.  (format check)&gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec]    
     [exec]    ✖ 1 problem (1 error, 0 warnings)
     [exec]    
     [exec]    
     [exec] 
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec] ❌ CI checks failed.  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec] 
     [exec] error Command failed with exit code 1.  at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [exec] Gradle build finished at 2024-10-23 18:03:46.738.
     [exec] 
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
     [exec]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)</pre></details></html>

2024-10-23 18:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6523/">test-portal-source-format#6523</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6523/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3750">liferay-bpm#3750</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/49995085">[master] ci:test:sf - vngoliveira &gt; liferay-bpm - PR#3750 - 2024-10-23[10:59:56]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>49995085<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/24924/">publish-testray-report#24924</a><br/></div></div>

2024-10-23 18:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:playwright - 0 out of 1 jobs passed in 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/449fa8fd0fbf5b9bbae254fdd8b549332370371e">449fa8fd0fbf5b9bbae254fdd8b549332370371e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/75cdfe67b3f03ae0eaaddbcb91187877e279f954">75cdfe67b3f03ae0eaaddbcb91187877e279f954</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/49946163">EE Development Acceptance (master) - 943 - 2024-10-23[07:21:16]</a></p><details><summary><strong>ci:test:playwright - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11526/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11526/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11526/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-10-23 18:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:forms - 1 out of 3 jobs passed in 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/449fa8fd0fbf5b9bbae254fdd8b549332370371e">449fa8fd0fbf5b9bbae254fdd8b549332370371e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/75cdfe67b3f03ae0eaaddbcb91187877e279f954">75cdfe67b3f03ae0eaaddbcb91187877e279f954</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/49946163">EE Development Acceptance (master) - 943 - 2024-10-23[07:21:16]</a></p><details><summary><strong>ci:test:forms - 1 out of 3 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12877/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>js-unit<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1121239/">js-unit/0/0</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1236842/"><strike>js-unit/1/0</strike></a></li></ul></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12877/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12877/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>1 Job Passed.<br/>2 Jobs Failed.</p></div><pre>[beanshell] Build "js-unit/1/0" started at https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1236842/.
[beanshell] Build "js-unit/0/0" completed at https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1121239/. SUCCESS
[beanshell] ParallelExecutor 2 - addDownstreamBuilds completed 2 tasks in 102 ms averaging 44 ms per task. 
[beanshell] Build model created in 2 seconds
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{routines (page: 1, pageSize: 1, filter: "id eq '590307'") \{items \{dateCreated dateModified id name routineToProjects \} page pageSize lastPage\}\}\} in 457 ms
[beanshell] Executing commands: git remote -v
[beanshell] Found Git remotes: github-dev, origin, upstream
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{builds (page: 1, pageSize: 25, filter: "r_routineToBuilds_c_routineId eq '590307'", sort: "dateCreated:desc") \{items \{dateCreated dateModified description dueDate dueStatus \{key name\} githubCompareURLs gitHash id name productVersionToBuilds projectToBuilds routineToBuilds \} page pageSize lastPage\}\}\} in 755 ms
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{projects (page: 1, pageSize: 1, filter: "id eq '35392'") \{items \{dateCreated dateModified description id name \} page pageSize lastPage\}\}\} in 385 ms
[beanshell] Executing commands: git merge-base --is-ancestor 75cdfe67b3f03ae0eaaddbcb91187877e279f954 HEAD
[beanshell] https://testray.liferay.com/o/graphql query: \{c \{caseResults (page: 1, pageSize: 5, filter: "r_buildToCaseResult_c_buildId eq '49946163'") \{items \{attachments buildToCaseResult caseToCaseResult componentToCaseResult dateCreated dateModified dueStatus \{ key name \} errors id startDate \} page pageSize lastPage\}\}\} in 565 ms
[beanshell] https://storage.cloud.google.com/testray-results/2024-10/test-1-40/test-portal-acceptance-upstream-dxp(master)/943/build-report.json.gz in 144 ms
[beanshell] Comparing with test results from https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/943 at SHA 75cdfe67b3f03ae0eaaddbcb91187877e279f954
[beanshell] Unable to create build anchor element. The process timed out while waiting for a build result for https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1236842/.
[beanshell] 
[beanshell] Unique Failures:
[beanshell] 
[beanshell] Upstream Failures:
[beanshell] Collected 0 downstream failure messages</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-10-23 18:31 UTC, igor-franca commented
Hey @vngoliveira, could you check the sf error? Seems related to your changes

2024-10-23 18:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/11526/">test-portal-acceptance-pullrequest(master)#11526</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11526/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>playwright<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3750">liferay-bpm#3750</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50036549">[master] ci:test:playwright - vngoliveira &gt; liferay-bpm - PR#3750 - 2024-10-23[11:00:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50036549<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/25206/">publish-testray-report#25206</a><br/></div></div>

2024-10-23 18:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12877/">test-portal-acceptance-pullrequest(master)#12877</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12877/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>forms<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3750">liferay-bpm#3750</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50036551">[master] ci:test:forms - vngoliveira &gt; liferay-bpm - PR#3750 - 2024-10-23[11:01:07]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50036551<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28149/">publish-testray-report#28149</a><br/></div></div>

2024-10-23 18:38 UTC, igor-franca commented
The error is not clear, but it is related to the file:
```

     [exec] âš™ï¸ Running TypeScript checks on modified files...
     [exec] â„¹ï¸ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] 
     [exec] âš™ï¸ Running format checks on modified files...
     [exec] /opt/dev/projects/github/liferay-portal/modules/test/playwright/tests/dynamic-data-mapping-form-web/formSubmission.spec.ts
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
```

2024-10-23 18:44 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 72 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/449fa8fd0fbf5b9bbae254fdd8b549332370371e">449fa8fd0fbf5b9bbae254fdd8b549332370371e</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/11623/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11623/jenkins-report.html">here</a>.</b></p>

2024-10-23 20:51 UTC, igor-franca commented
resent [here](https://github.com/liferay-bpm/liferay-portal/pull/3775)

2024-10-23 20:51 UTC, closed without merging