LPD-39807
liferay-bpm/liferay-portal pull request #3784
Opened 2024-10-25 15:06 UTC by rijema

https://liferay.atlassian.net/browse/LPD-39807

2024-10-25 15:08 UTC, rijema commented
Previous: https://github.com/liferay-bpm/liferay-portal/pull/3769

2024-10-25 15:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10432/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10432/jenkins-report.html">here</a>.</b></p>

2024-10-25 15:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d76fbecadb69feabeb9c3527a66d830e5eef7587">d76fbecadb69feabeb9c3527a66d830e5eef7587</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rijema/liferay-portal/tree/LPD-39807-5">LPD-39807-5</a><br/>Branch GIT ID: <a href="https://github.com/rijema/liferay-portal/commit/5dd588238224a9db6a1a0b636c07ebe0a33919d8">5dd588238224a9db6a1a0b636c07ebe0a33919d8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10432/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10432/jenkins-report.html">here</a>.</h5></details></html>

2024-10-25 15:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10432/">test-portal-source-format#10432</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10432/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3784">liferay-bpm#3784</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/52401399">[master] ci:test:sf - rijema &gt; liferay-bpm - PR#3784 - 2024-10-25[08:08:33]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>52401399<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/39816/">publish-testray-report#39816</a><br/></div></div>

2024-10-25 15:22 UTC, rijema commented
ci:test:sf

2024-10-25 15:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10433/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10433/jenkins-report.html">here</a>.</b></p>

2024-10-25 15:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d76fbecadb69feabeb9c3527a66d830e5eef7587">d76fbecadb69feabeb9c3527a66d830e5eef7587</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rijema/liferay-portal/tree/LPD-39807-5">LPD-39807-5</a><br/>Branch GIT ID: <a href="https://github.com/rijema/liferay-portal/commit/b6d5640ddbdaf99bd45fb530e7f898b884b352ba">b6d5640ddbdaf99bd45fb530e7f898b884b352ba</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10433/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10433/jenkins-report.html">here</a>.</h5></details></html>

2024-10-25 15:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10433/">test-portal-source-format#10433</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10433/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3784">liferay-bpm#3784</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/52446516">[master] ci:test:sf - rijema &gt; liferay-bpm - PR#3784 - 2024-10-25[08:23:10]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>52446516<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/39817/">publish-testray-report#39817</a><br/></div></div>

2024-10-29 03:26 UTC, guilhermedcamacho requested changes
Please also change this [commit message](https://github.com/liferay-bpm/liferay-portal/pull/3784/commits/7d6c75eb914dedc3cb9151c7fb004b2f8c1a3919) to buildService.

2024-10-29 03:26 UTC, guilhermedcamacho commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/registry/DDMServiceUpgradeStepRegistrator.java
> +					return new String[][] {{"DDMStructure", "structureId"}};
Should we use `structureId` for `primKeyColumnName` here?

2024-10-29 03:26 UTC, guilhermedcamacho commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/testIntegration/java/com/liferay/dynamic/data/mapping/service/test/DDMStructureLocalServiceTest.java
> +	public void testAddDDMStructureWithExistingExternalReferenceCode()
You should cover this scenario inside the method `testAddDDMStructure()` using `AssertUtils.assertFailure`. You can see an example on class `ObjectDefinitionLocalServiceTest.java`

2024-10-29 03:26 UTC, guilhermedcamacho commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/testIntegration/java/com/liferay/dynamic/data/mapping/service/test/DDMStructureLocalServiceTest.java
> +	public void testDeleteNonexistingDDMStructureByExternalReferenceCode()
You should cover this scenario inside the method `testDeleteDDMStructureByExternalReferenceCode()` using `AssertUtils.assertFailure`.

2024-10-29 03:26 UTC, guilhermedcamacho commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/testIntegration/java/com/liferay/dynamic/data/mapping/service/test/DDMStructureLocalServiceTest.java
> +	public void testUpdateDDMStructureWithExistingExternalReferenceCode()
You should cover this scenario inside the method `testUpdateDDMStructure()` using `AssertUtils.assertFailure`.

2024-10-29 17:30 UTC, rijema commented
@guilhermedcamacho please see https://github.com/liferay-bpm/liferay-portal/pull/3794

2024-10-29 17:30 UTC, closed without merging