LPD-41065
liferay-bpm/liferay-portal pull request #3827
Opened 2024-11-06 17:38 UTC by vngoliveira

[LPD-36658](https://liferay.atlassian.net/browse/LPD-36658)

2024-11-06 17:38 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-06 17:39 UTC, vngoliveira commented
Hey team!
I am sending these first changes to be reviewed while I am working on the integration test and the upgrade test

2024-11-06 18:01 UTC, carolmariaabb requested changes

2024-11-06 18:01 UTC, carolmariaabb commented on modules/apps/object/object-rest-test/src/testFunctional/macros/ObjectDefinitionAPI.macro
> +	}
@vngoliveira could you please change to be `_getObjectDefinitionPortletId` returning:

```
return "com_liferay_object_web_internal_object_definitions_portlet_ObjectDefinitionsPortlet_${objectDefinitionClassNameSuffix}";
```
?

2024-11-06 18:01 UTC, carolmariaabb commented on modules/apps/site-initializer/site-initializer-welcome/src/main/resources/site-initializer/layout-utility-page-entries/cookie-policy/page-definition.json
>  															}
@vngoliveira same logic here, change from `OBJECT_DEFINITION_CLASS_NAME_SUFFIX` to `OBJECT_DEFINITION_PORTLET_ID`

2024-11-07 12:36 UTC, carolmariaabb requested changes

2024-11-07 12:36 UTC, carolmariaabb commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
>  					serviceBuilderObjectDefinition.getShortName(),
@vngoliveira `OBJECT_DEFINITION_PORTLET_ID` should be after `OBJECT_DEFINITION_ID` to follow alphabetical order

2024-11-07 12:36 UTC, carolmariaabb commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
>  			stringUtilReplaceValues.put(
@vngoliveira same here

2024-11-07 12:36 UTC, carolmariaabb commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
@vngoliveira please create a private method to reuse code:

```
private void _addObjectDefinition(
	String objectDefinitionClassName, long objectDefinitionId,
	String objectDefinitionName,
	Map<String, String> stringUtilReplaceValues) {

	stringUtilReplaceValues.put(
		"OBJECT_DEFINITION_CLASS_NAME:" + objectDefinitionName,
		objectDefinitionClassName);
	stringUtilReplaceValues.put(
		"OBJECT_DEFINITION_ID:" + objectDefinitionName,
		String.valueOf(objectDefinitionId));
	stringUtilReplaceValues.put(
		"OBJECT_DEFINITION_PORTLET_ID:" + objectDefinitionName,
		ObjectPortletKeys.OBJECT_DEFINITIONS +
			StringUtil.split(objectDefinitionClassName, StringPool.POUND)
				[1]);
}
```

2024-11-08 12:12 UTC, vngoliveira commented
ci:test:sf

2024-11-08 12:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10577/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10577/jenkins-report.html">here</a>.</b></p>

2024-11-08 12:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10577/">test-portal-source-format#10577</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10577/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3827">liferay-bpm#3827</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/63580049">[master] ci:test:sf - vngoliveira &gt; liferay-bpm - PR#3827 - 2024-11-08[04:12:21]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>63580049<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/40262/">publish-testray-report#40262</a><br/></div></div>

2024-11-08 18:11 UTC, closed without merging

2024-11-08 18:11 UTC, carolmariaabb commented
@vngoliveira see https://github.com/liferay-bpm/liferay-portal/pull/3841