LPD-41238
liferay-bpm/liferay-portal pull request #3900
Opened 2024-11-22 20:05 UTC by JhossephG

2024-11-22 20:05 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-11-22 20:06 UTC, JhossephG commented
ci:test:sf

2024-11-22 20:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/7613/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7613/jenkins-report.html">here</a>.</b></p>

2024-11-22 20:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/846af5c78589d3f3bedf9a5942139f823409113c">846af5c78589d3f3bedf9a5942139f823409113c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPD-41238">LPD-41238</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/efa65e697e45be78315338716d2ca2d09b902438">efa65e697e45be78315338716d2ca2d09b902438</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7613/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7613/jenkins-report.html">here</a>.</h5></details></html>

2024-11-22 20:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7613/">test-portal-source-format#7613</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7613/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3900">liferay-bpm#3900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/74972019">[master] ci:test:sf - JhossephG &gt; liferay-bpm - PR#3900 - 2024-11-22[12:08:29]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>74972019<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/5357/">publish-testray-report#5357</a><br/></div></div>

2024-11-25 11:33 UTC, JhossephG commented
ci:test:sf

2024-11-25 11:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7534/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7534/jenkins-report.html">here</a>.</b></p>

2024-11-25 11:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/943e75c70437607fff2c6a98ab8a4e38b42a51bb">943e75c70437607fff2c6a98ab8a4e38b42a51bb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPD-41238">LPD-41238</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/1d92b57b1bdb9fd40c15be62d43d58f924d9f1e2">1d92b57b1bdb9fd40c15be62d43d58f924d9f1e2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7534/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7534/jenkins-report.html">here</a>.</h5></details></html>

2024-11-25 11:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7534/">test-portal-source-format#7534</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7534/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3900">liferay-bpm#3900</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/76428436">[master] ci:test:sf - JhossephG &gt; liferay-bpm - PR#3900 - 2024-11-25[03:33:26]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>76428436<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/28704/">publish-testray-report#28704</a><br/></div></div>

2024-11-25 12:56 UTC, MarinhoFeliphe requested changes
Hey @JhossephG after doing these changes, if you have already checked the failures and they are not related you can forward to brian's repo.

Thanks

2024-11-25 12:56 UTC, MarinhoFeliphe commented on modules/apps/portal-workflow/portal-workflow-test/src/testIntegration/java/com/liferay/portal/workflow/service/test/WorkflowDefinitionLinkServiceImplTest.java
> +	}
@JhossephG do [this way](https://github.com/liferay/liferay-portal/blob/71e281da80b10a75a45644c0529dd1de3bacba67/modules/apps/portal-workflow/portal-workflow-kaleo-test/src/testIntegration/java/com/liferay/portal/workflow/kaleo/service/test/KaleoDefinitionServiceImplTest.java#L111) to keep the pattern.

Thank you!

2024-11-25 13:46 UTC, closed without merging

2024-11-25 13:47 UTC, JhossephG commented
sent to BChan [here](https://github.com/brianchandotcom/liferay-portal/pull/156406)