LPD-43173
liferay-bpm/liferay-portal pull request #3937
Opened 2024-12-05 20:59 UTC by JhossephG

2024-12-05 20:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-12-05 21:02 UTC, JhossephG commented
ci:test:sf

2024-12-05 21:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/7612/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7612/jenkins-report.html">here</a>.</b></p>

2024-12-05 21:06 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPD-43173">LPD-43173</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/1b7f66be34d894e44bb39387e19231f3ce70d0e6">1b7f66be34d894e44bb39387e19231f3ce70d0e6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/7612/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/7612/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Incorrect commit message: Missing breaking change in commit messages when the major version bumps up: ./portal-kernel/bnd.bnd (SourceCheck:BNDBreakingChangeCommitMessageCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:49.286 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1529843304.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null189754924
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 152ms
[junitreport] Deleting: /tmp/null189754924
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-05-2024 13:06:38:711 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1529843304.properties

print-gc-logs:
     [echo] 
     [echo] ##
     [echo] ## /tmp/ant-gc.log
     [echo] ##
     [echo] </pre></details></html>

2024-12-06 13:50 UTC, linolaoj commented
Hi @JhossephG , sf says it is _Missing breaking change in commit messages_. Can you please check it?

2024-12-06 17:45 UTC, linolaoj requested changes

2024-12-06 17:45 UTC, linolaoj commented on portal-impl/src/com/liferay/portal/service/impl/WorkflowDefinitionLinkLocalServiceImpl.java
> +	private WorkflowDefinitionLink _createAndConfigureWorkflowDefinitionLink(
Hi @JhossephG , since this method is used only once, can it be inline?

2024-12-06 17:45 UTC, linolaoj commented on portal-impl/src/com/liferay/portal/service.xml
> +		<finder name="G_C_C_WDN" return-type="WorkflowDefinitionLink" unique="true">
@JhossephG , should this be G_C_C_W?

2024-12-06 18:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/7633/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7633/jenkins-report.html">here</a>.</b></p>

2024-12-06 18:01 UTC, JhossephG commented
ci:stop

2024-12-06 18:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c21da3ceadf0abb80f3a284d05771a40671999b">8c21da3ceadf0abb80f3a284d05771a40671999b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPD-43173">LPD-43173</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/ecf3693d9d059467cd88e39d1f8b30b1af7ea1f5">ecf3693d9d059467cd88e39d1f8b30b1af7ea1f5</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7633/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7633/jenkins-report.html">here</a>.</h5><pre>stop-current-job:
     [echo] stop.current.job.start.timestamp: 12-06-2024 10:01:36:757 PST
[beanshell] 'stop-current-job' will timeout in 30 minutes
[beanshell] Created cache file in /tmp/jenkins-cached-files/-734713972.txt
[beanshell] Unable to find downstream builds in build-database.json
[beanshell] 4229 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 31 minutes.
[beanshell]     https://api.github.com/repos/liferay-bpm/liferay-portal/pulls/3937
[beanshell] 4228 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 31 minutes.
[beanshell]     https://github-proxy-ujidqcdz2q-wl.a.run.app/repos/liferay-bpm/liferay-portal/issues/comments/2523868173
[beanshell] 4227 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 31 minutes.
[beanshell]     https://github-proxy-ujidqcdz2q-wl.a.run.app/repos/liferay-bpm/liferay-portal/issues/3937/labels/ci%3Atest%3Asf%20%20-%20pending
[beanshell] 4226 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 31 minutes.
[beanshell]     https://api.github.com/repos/liferay-bpm/liferay-portal/labels?per_page=100&amp;page=1
[beanshell] 4225 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 31 minutes.
[beanshell]     https://api.github.com/repos/liferay-bpm/liferay-portal/labels?per_page=100&amp;page=2
[beanshell] 4224 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 31 minutes.
[beanshell]     https://api.github.com/repos/liferay-bpm/liferay-portal/pulls/3937
[beanshell] 4222 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 31 minutes.
[beanshell]     https://github-proxy-ujidqcdz2q-wl.a.run.app/repos/liferay-bpm/liferay-portal/issues/3937/labels
     [exec] 
     [exec] &gt; Task :setUpYarnOfflineCache
     [exec] Checking Yarn binaries cache directories
[beanshell] 4219 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 31 minutes.
[beanshell]     https://github-proxy-ujidqcdz2q-wl.a.run.app/repos/liferay-bpm/liferay-portal/statuses/ecf3693d9d059467cd88e39d1f8b30b1af7ea1f5</pre></details></html>

2024-12-06 18:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7633/">test-portal-source-format#7633</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7633/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3937">liferay-bpm#3937</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/85854531">[master] ci:test:sf - JhossephG &gt; liferay-bpm - PR#3937 - 2024-12-06[09:58:47]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>85854531<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/5378/">publish-testray-report#5378</a><br/></div></div>

2024-12-06 18:42 UTC, JhossephG commented
ci:test:sf

2024-12-06 18:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6952/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6952/jenkins-report.html">here</a>.</b></p>

2024-12-06 18:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c21da3ceadf0abb80f3a284d05771a40671999b">8c21da3ceadf0abb80f3a284d05771a40671999b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPD-43173">LPD-43173</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/2d8138965f3da34495d3edc6c9f1731e8cabc949">2d8138965f3da34495d3edc6c9f1731e8cabc949</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6952/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6952/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-kernel/src/com/liferay/portal/kernel/exception/DuplicateWorkflowDefinitionLinkExternalReferenceCodeException.java expected:&lt;...A-2.0.0-2023-06
     [java]  */
     [java] [
     [java] package com.liferay.portal.kernel.exception;
     [java] 
     [java] /**
     [java]  * @author Brian Wing Shun Chan
     [java]  */
     [java] public class DuplicateWorkflowDefinitionLinkExternalReferenceCodeException
     [java]   extends DuplicateExternalReferenceCodeException \{
     [java] 
     [java]   public DuplicateWorkflowDefinitionLinkExternalReferenceCodeException() \{
     [java]   \}
     [java] 
     [java]   public DuplicateWorkflowDefinitionLinkExternalReferenceCodeException(
     [java]     String msg) \{
     [java] 
     [java]     super(msg);
     [java]   \}
     [java] 
     [java]   public DuplicateWorkflowDefinitionLinkExternalReferenceCodeException(
     [java]     String msg, Throwable throwable) \{
     [java] 
     [java]     super(msg, throwable);
     [java]   \}
     [java] 
     [java]   public DuplicateWorkflowDefinitionLinkExternalReferenceCodeException(
     [java]     Throwable throwable) \{
     [java] ]
     [java]     super(throwable);...&gt; but was:&lt;...A-2.0.0-2023-06
     [java]  */
     [java] [package com.liferay.portal.kernel.exception;
     [java] 
     [java] import com.liferay.portal.kernel.exception.DuplicateExternalReferenceCodeException;
     [java] 
     [java] /**
     [java]  * @author Brian Wing Shun Chan
     [java]  */
     [java] public class DuplicateWorkflowDefinitionLinkExternalReferenceCodeException extends DuplicateExternalReferenceCodeException \{
     [java] 
     [java]   public DuplicateWorkflowDefinitionLinkExternalReferenceCodeException() \{
     [java]   \}
     [java] 
     [java]   public DuplicateWorkflowDefinitionLinkExternalReferenceCodeException(String msg) \{
     [java]     super(msg);
     [java]   \}
     [java] 
     [java]   public DuplicateWorkflowDefinitionLinkExternalReferenceCodeException(String msg, Throwable throwable) \{
     [java]     super(msg, throwable);
     [java]   \}
     [java] 
     [java]   public DuplicateWorkflowDefinitionLinkExternalReferenceCodeException(Throwable throwable) \{]
     [java]     super(throwable);...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)</pre></details></html>

2024-12-06 18:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6952/">test-portal-source-format#6952</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6952/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3937">liferay-bpm#3937</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/85888716">[master] ci:test:sf - JhossephG &gt; liferay-bpm - PR#3937 - 2024-12-06[10:42:50]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>85888716<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/26462/">publish-testray-report#26462</a><br/></div></div>

2024-12-06 18:53 UTC, JhossephG commented
ci:test:sf

2024-12-06 18:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5829/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5829/jenkins-report.html">here</a>.</b></p>

2024-12-06 19:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c21da3ceadf0abb80f3a284d05771a40671999b">8c21da3ceadf0abb80f3a284d05771a40671999b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPD-43173">LPD-43173</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/a1a1fe98a89f88397d94171c93968657b07e00eb">a1a1fe98a89f88397d94171c93968657b07e00eb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5829/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5829/jenkins-report.html">here</a>.</h5></details></html>

2024-12-06 19:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5829/">test-portal-source-format#5829</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5829/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3937">liferay-bpm#3937</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/85913426">[master] ci:test:sf - JhossephG &gt; liferay-bpm - PR#3937 - 2024-12-06[10:55:28]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>85913426<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/6451/">publish-testray-report#6451</a><br/></div></div>

2024-12-09 10:52 UTC, JhossephG commented
ci:test:relevant

2024-12-09 10:52 UTC, JhossephG commented
ci:test:sf

2024-12-09 14:22 UTC, JhossephG commented
ci:test:relevant

2024-12-09 14:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/7012/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7012/jenkins-report.html">here</a>.</b></p>

2024-12-09 14:29 UTC, linolaoj requested changes

2024-12-09 14:29 UTC, linolaoj commented on portal-impl/src/com/liferay/portal/service/impl/WorkflowDefinitionLinkLocalServiceImpl.java
> +			String className, Long groupId,
Hi @JhossephG , the className should come after the groupId, that is the order on service.xml and the other methods in this class. Please, after updating also check the usages.

2024-12-09 14:29 UTC, linolaoj commented on modules/apps/headless/headless-admin-workflow/headless-admin-workflow-impl/src/main/java/com/liferay/headless/admin/workflow/internal/resource/v1_0/WorkflowDefinitionLinkResourceImpl.java
> +			Group group = _groupService.fetchGroupByExternalReferenceCode(
Hi @JhossephG , since we are throwing the `noSuchGroupException` we can use the `getGroupByExternalReferenceCode` to avoid the check of `null`.

2024-12-09 14:32 UTC, liferay-continuous-integration commented
ci:test:upgrade

Invoking upgrade test suite because an upgrade file has been modified.

2024-12-09 14:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>upgrade</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19114/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19114/jenkins-report.html">here</a>.</b></p>

2024-12-09 16:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:upgrade - 224 out of 394 jobs passed in 1 hour 37 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/87398872">EE Development Acceptance (master) - 1069 - 2024-12-09[00:38:54]</a></p><details><summary><strong>ci:test:upgrade - 224 out of 394 jobs PASSED</strong></summary><div><h4>170 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19114/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-db2111<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985939/">functional-tomcat90-db2111/0/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388723/">functional-tomcat90-db2111/1/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449127/">functional-tomcat90-db2111/1/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/398050/">functional-tomcat90-db2111/1/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385140/">functional-tomcat90-db2111/1/3</a></li></ul></li><li>functional-tomcat90-mariadb102<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1139777/">functional-tomcat90-mariadb102/0/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/398045/">functional-tomcat90-mariadb102/1/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449122/">functional-tomcat90-mariadb102/1/1</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385135/">functional-tomcat90-mariadb102/1/2</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495052/">functional-tomcat90-mariadb102/1/3</a></li></ul></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/992927/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1246369/"><strike>functional-tomcat90-mysql57/0/1</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/728872/"><strike>functional-tomcat90-mysql57/0/2</strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498360/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495035/"><strike>functional-tomcat90-mysql57/1/1</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495034/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/468979/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498358/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495033/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498357/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495032/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/468978/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498359/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388709/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385127/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/495044/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449114/">functional-tomcat90-mysql57/1/13</a></li></ul></li><li>functional-tomcat90-mysql80<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/992940/">functional-tomcat90-mysql80/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985942/"><strike>functional-tomcat90-mysql80/0/1</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/728880/"><strike>functional-tomcat90-mysql80/0/2</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444517/">functional-tomcat90-mysql80/1/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/468986/">functional-tomcat90-mysql80/1/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388706/">functional-tomcat90-mysql80/1/2</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453712/">functional-tomcat90-mysql80/1/3</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449111/">functional-tomcat90-mysql80/1/4</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/398034/">functional-tomcat90-mysql80/1/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/498368/">functional-tomcat90-mysql80/1/6</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/398036/">functional-tomcat90-mysql80/1/7</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388707/">functional-tomcat90-mysql80/1/8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/444518/">functional-tomcat90-mysql80/1/9</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/398049/">functional-tomcat90-mysql80/1/10</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/385139/">functional-tomcat90-mysql80/1/11</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449126/">functional-tomcat90-mysql80/1/12</a></li></ul></li><li>functional-tomcat90-oracle193<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/985940/">functional-tomcat90-oracle193/0/0</a></li><li><a href="https://test [...]

2024-12-09 16:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19114/">test-portal-acceptance-pullrequest(master)#19114</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19114/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>upgrade<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3937">liferay-bpm#3937</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/87636872">[master] ci:test:upgrade - JhossephG &gt; liferay-bpm - PR#3937 - 2024-12-09[06:32:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>87636872<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/41326/">publish-testray-report#41326</a><br/></div></div>

2024-12-09 16:42 UTC, JhossephG commented
ci:test:sf

2024-12-09 16:44 UTC, JhossephG commented
ci:test:relevant

2024-12-09 16:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c">c0fe70e42b05ef5b2bc5d25bd127810e7a64eb7c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JhossephG/liferay-portal/tree/LPD-43173">LPD-43173</a><br/>Branch GIT ID: <a href="https://github.com/JhossephG/liferay-portal/commit/e356a505950fbceb9fdc9cd4e7052caa55bb7f92">e356a505950fbceb9fdc9cd4e7052caa55bb7f92</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3813/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3813/jenkins-report.html">here</a>.</h5></details></html>

2024-12-09 16:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/7110/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7110/jenkins-report.html">here</a>.</b></p>

2024-12-09 17:00 UTC, closed without merging

2024-12-09 17:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/7012/">test-portal-acceptance-pullrequest(master)#7012</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7012/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3937">liferay-bpm#3937</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/87660036">[master] ci:test:relevant - JhossephG &gt; liferay-bpm - PR#3937 - 2024-12-09[06:22:19]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>87660036<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/15617/">publish-testray-report#15617</a><br/></div></div>

2024-12-09 17:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/7110/">test-portal-acceptance-pullrequest(master)#7110</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7110/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3937">liferay-bpm#3937</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/87660038">[master] ci:test:relevant - JhossephG &gt; liferay-bpm - PR#3937 - 2024-12-09[08:54:41]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>87660038<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/15603/">publish-testray-report#15603</a><br/></div></div>

2024-12-09 17:31 UTC, JhossephG commented
resent [here](https://github.com/liferay-bpm/liferay-portal/pull/3949)