LPD-40798
liferay-bpm/liferay-portal pull request #3943
Opened 2024-12-06 18:13 UTC by rijema

Related issue: https://liferay.atlassian.net/browse/LPD-40798

2024-12-06 18:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-12-06 18:13 UTC, rijema commented
ci:test:sf

2024-12-06 18:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3805/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3805/jenkins-report.html">here</a>.</b></p>

2024-12-06 18:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c21da3ceadf0abb80f3a284d05771a40671999b">8c21da3ceadf0abb80f3a284d05771a40671999b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rijema/liferay-portal/tree/LDP-40798-5">LDP-40798-5</a><br/>Branch GIT ID: <a href="https://github.com/rijema/liferay-portal/commit/2f281e18fcd54c0a4fd6b7bc243d2fada9812cf7">2f281e18fcd54c0a4fd6b7bc243d2fada9812cf7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3805/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3805/jenkins-report.html">here</a>.</h5></details></html>

2024-12-06 18:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3805/">test-portal-source-format#3805</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3805/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3943">liferay-bpm#3943</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/85861481">[master] ci:test:sf - rijema &gt; liferay-bpm - PR#3943 - 2024-12-06[10:13:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>85861481<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/15581/">publish-testray-report#15581</a><br/></div></div>

2024-12-06 18:28 UTC, rijema commented
@marcelabc , the changes were done. Thank you!

2024-12-06 18:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10850/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10850/jenkins-report.html">here</a>.</b></p>

2024-12-06 18:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c21da3ceadf0abb80f3a284d05771a40671999b">8c21da3ceadf0abb80f3a284d05771a40671999b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rijema/liferay-portal/tree/LDP-40798-5">LDP-40798-5</a><br/>Branch GIT ID: <a href="https://github.com/rijema/liferay-portal/commit/fb811ffcf9c454167cb9e4c1a11e3e238f871169">fb811ffcf9c454167cb9e4c1a11e3e238f871169</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10850/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10850/jenkins-report.html">here</a>.</h5></details></html>

2024-12-06 18:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10850/">test-portal-source-format#10850</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10850/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/3943">liferay-bpm#3943</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/85879153">[master] ci:test:sf - rijema &gt; liferay-bpm - PR#3943 - 2024-12-06[10:27:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>85879153<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/41215/">publish-testray-report#41215</a><br/></div></div>

2024-12-09 11:54 UTC, rijema commented
Conflict solved.

2024-12-09 13:10 UTC, marcelabc requested changes
Hi 
I finished my review. Let me know if you have questions :smile:

2024-12-09 13:10 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectEntryLocalServiceTest.java
> +		// Object entry with unique values in a company scoped object definition
Rename:
// Object entry with unique values in the same company

2024-12-09 13:10 UTC, marcelabc commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectEntryLocalServiceTest.java
> +		// Object entry with unique values in a company scoped object definition
After this renaming, you will need to reorder the test :disappointed: 

```
// Object entry with localized values
// Object entry with the same external reference code in different sites
// Object entry with the same external reference code in the same company
// Object entry with unique values in the same company
// Object entry with unique values in different sites
// Object entry with unique values in the same site
```

2024-12-11 20:46 UTC, rijema commented
Update available here: https://github.com/liferay-bpm/liferay-portal/pull/3965

2024-12-11 20:46 UTC, closed without merging