LPD-44371
liferay-bpm/liferay-portal pull request #4016
Opened 2024-12-27 16:59 UTC by pedro-oliveira446

2024-12-27 16:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-12-27 17:05 UTC, pedro-oliveira446 commented
ci:test:sf

2024-12-27 17:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/7468/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7468/jenkins-report.html">here</a>.</b></p>

2024-12-27 17:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e0dd68395f016fbfd91c7a291ea49b0330f1d02b">e0dd68395f016fbfd91c7a291ea49b0330f1d02b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-44371">LPD-44371</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/c4d64f8ed57c90d64e833982ada27bbdc18c8653">c4d64f8ed57c90d64e833982ada27bbdc18c8653</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7468/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7468/jenkins-report.html">here</a>.</h5></details></html>

2025-01-02 18:20 UTC, gabrielwas requested changes
@pedro-oliveira446 weel done! Check the minor changes.

2025-01-02 18:20 UTC, gabrielwas commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectDefinitionLocalServiceImpl.java
> +	public void deployObjectDefinitions() {
@pedro-oliveira446 override is missing, right?

2025-01-02 18:20 UTC, gabrielwas commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectDefinitionLocalServiceTest.java
> +				NotificationHandler.class.getName(),
Better checking here the `PersistedModelLocalService`. It makes more sense than the notification one.

2025-01-02 21:43 UTC, pedro-oliveira446 commented
ci:test:sf

2025-01-02 21:43 UTC, pedro-oliveira446 commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectDefinitionLocalServiceImpl.java
> +	public void deployObjectDefinitions() {
Just done!

2025-01-02 21:43 UTC, pedro-oliveira446 commented on modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectDefinitionLocalServiceTest.java
> +				NotificationHandler.class.getName(),
Done!

2025-01-02 21:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/7138/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7138/jenkins-report.html">here</a>.</b></p>

2025-01-02 21:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/258b446ec7dca008a43cac74248f9bc0f2ef18d1">258b446ec7dca008a43cac74248f9bc0f2ef18d1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/pedro-oliveira446/liferay-portal/tree/LPD-44371">LPD-44371</a><br/>Branch GIT ID: <a href="https://github.com/pedro-oliveira446/liferay-portal/commit/4d82469c225962df6294d84af914e2da87d8f7d0">4d82469c225962df6294d84af914e2da87d8f7d0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/7138/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7138/jenkins-report.html">here</a>.</h5></details></html>

2025-01-02 21:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/7138/">test-portal-source-format#7138</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/7138/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/4016">liferay-bpm#4016</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/102461058">[master] ci:test:sf - pedro-oliveira446 &gt; liferay-bpm - PR#4016 - 2025-01-02[13:43:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>102461058<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/26394/">publish-testray-report#26394</a><br/></div></div>

2025-01-03 14:59 UTC, gabrielwas approved these changes
Good! @pedro-oliveira446

2025-01-03 16:03 UTC, pedro-oliveira446 commented
ci:test:relevant

2025-01-03 16:03 UTC, pedro-oliveira446 commented
ci:test:object

2025-01-03 16:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>object</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19508/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19508/jenkins-report.html">here</a>.</b></p>

2025-01-03 17:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 24 out of 25 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 30 out of 32 jobs passed in 1 hour 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca3c21cd937a23561f115578041279038a160b83">ca3c21cd937a23561f115578041279038a160b83</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca3c21cd937a23561f115578041279038a160b83">ca3c21cd937a23561f115578041279038a160b83</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/102961637">EE Development Acceptance (master) - 1115 - 2025-01-03[04:36:09]</a></p><details><summary><strong>ci:test:stable - 24 out of 25 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>central-requirements<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153205/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286515/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814758/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113818/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1256028/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814741/">js-unit/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814742/"><strike>js-unit/1/0</strike></a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1004017/">modules-compile/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162597/">modules-compile/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153223/">modules-compile/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049082/">modules-compile/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055828/">modules-compile/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983590/">modules-compile/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153222/">modules-compile/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286516/">modules-compile/0/7</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/992866/">modules-compile/0/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162369/">modules-compile/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814757/">modules-compile/0/10</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045199/">modules-compile/0/11</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1086845/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286517/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153221/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286514/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>service-builder<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286499/">service-builder/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153220/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 29 out of 32 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19507/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153205/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286515/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814758/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113818/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1256028/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814741/">js-unit/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814742/"><strike>js-unit/1/0</strike></a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1004017/">modules-compile/0/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162597/">modules-compile/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153223/">modules-compile/0/2</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049082/">modules-compile/0/3</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055828/">modules-compile/0/4</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983590/">modules-compile/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153222/">modules-compile/0/6</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286516/">modules-compile/0/7</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/992866/">modules-compile/0/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-port [...]

2025-01-03 17:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19507/">test-portal-acceptance-pullrequest(master)#19507</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19507/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/4016">liferay-bpm#4016</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/103052276">[master] ci:test:relevant - pedro-oliveira446 &gt; liferay-bpm - PR#4016 - 2025-01-03[08:03:36]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>103052276<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/42167/">publish-testray-report#42167</a><br/></div></div>

2025-01-03 18:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:object - 301 out of 322 jobs passed in 2 hours 46 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca3c21cd937a23561f115578041279038a160b83">ca3c21cd937a23561f115578041279038a160b83</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ca3c21cd937a23561f115578041279038a160b83">ca3c21cd937a23561f115578041279038a160b83</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/102961637">EE Development Acceptance (master) - 1115 - 2025-01-03[04:36:09]</a></p><details><summary><strong>ci:test:object - 301 out of 322 jobs PASSED</strong></summary><div><h4>21 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19508/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814765/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113824/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045206/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738645/">functional-tomcat90-mysql57/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162602/">functional-tomcat90-mysql57/0/4</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049087/">functional-tomcat90-mysql57/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162601/">functional-tomcat90-mysql57/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153229/">functional-tomcat90-mysql57/0/7</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055834/">functional-tomcat90-mysql57/0/8</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045205/">functional-tomcat90-mysql57/0/9</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061824/">functional-tomcat90-mysql57/0/10</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1004029/">functional-tomcat90-mysql57/0/11</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458555/">functional-tomcat90-mysql57/0/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162610/">functional-tomcat90-mysql57/0/13</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814773/">functional-tomcat90-mysql57/0/14</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1086858/">functional-tomcat90-mysql57/0/15</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/992879/">functional-tomcat90-mysql57/0/16</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738653/">functional-tomcat90-mysql57/0/17</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1256041/">functional-tomcat90-mysql57/0/18</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1153238/">functional-tomcat90-mysql57/0/19</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045209/"><strike>functional-tomcat90-mysql57/0/20</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113827/">functional-tomcat90-mysql57/0/21</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286525/">functional-tomcat90-mysql57/0/22</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814769/">functional-tomcat90-mysql57/0/23</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162378/">functional-tomcat90-mysql57/0/24</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162599/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113820/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814761/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738642/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162598/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286518/"><strike>functional-tomcat90-mysql57/1/5</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738641/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049084/"><strike>functional-tomcat90-mysql57/1/7</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1004018/"><strike>functional-tomcat90-mysql57/1/8</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045202/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162380/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/474553/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/500538/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1286527/">functional-tomcat90-mysql57/1/13</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/503979/">functional-tomcat90-mysql57/1/14</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1049093/">functional-tomcat90-mysql57/1/15</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055840/">functional-tomcat90-mysql57/1/16</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061821/">functional-tomcat90-mysql57/1/17</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738650/">functional-tomcat90-mysql57/1/18</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1045210/">functional-tomcat90-mysql57/1/19</a></li><li><a href="htt [...]

2025-01-03 18:54 UTC, pedro-oliveira446 commented
ci:report:103052276

2025-01-03 18:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>103052276</b>.</p><p>Job Link: <a href="https://test-1-37.liferay.com/job/generate-testray-csv/580/">generate-testray-csv</a></p>

2025-01-03 18:55 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>103052276</b>.</p><p>Job Link: <a href="https://test-1-37.liferay.com/job/generate-testray-csv/580/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/580/testray-results-103052276.csv">testray-results-103052276.csv</a></p>

2025-01-03 18:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/19508/">test-portal-acceptance-pullrequest(master)#19508</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/19508/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>object<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/4016">liferay-bpm#4016</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/103059509">[master] ci:test:object - pedro-oliveira446 &gt; liferay-bpm - PR#4016 - 2025-01-03[08:03:46]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>103059509<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/42172/">publish-testray-report#42172</a><br/></div></div>

2025-01-03 19:00 UTC, pedro-oliveira446 commented
ci:report:103059509

2025-01-03 19:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>103059509</b>.</p><p>Job Link: <a href="https://test-1-37.liferay.com/job/generate-testray-csv/581/">generate-testray-csv</a></p>

2025-01-03 19:01 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Job Link: <a href="https://test-1-37.liferay.com/job/generate-testray-csv/581/">generate-testray-csv</a></p><p>Unable to generate report for testrayBuildID: <b>103059509</b>.</p><p>Please verify the testrayBuildID is correct, there are failures, and the respective testray build has results imported. If the results are not imported, rerun <b>ci:report:103059509</b> in 10-30 minutes.</p>

2025-01-03 19:15 UTC, pedro-oliveira446 commented
ci:report:103059509

2025-01-03 19:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>103059509</b>.</p><p>Job Link: <a href="https://test-1-39.liferay.com/job/generate-testray-csv/561/">generate-testray-csv</a></p>

2025-01-03 19:17 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>103059509</b>.</p><p>Job Link: <a href="https://test-1-39.liferay.com/job/generate-testray-csv/561/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/561/testray-results-103059509.csv">testray-results-103059509.csv</a></p>

2025-01-03 19:26 UTC, closed without merging

2025-01-03 19:27 UTC, pedro-oliveira446 commented
Resent https://github.com/brianchandotcom/liferay-portal/pull/157441