LPD-45168
liferay-bpm/liferay-portal pull request #4018
Opened 2024-12-27 19:33 UTC by vngoliveira

[LPD-45168](https://liferay.atlassian.net/browse/LPD-45168)

Hey team,
because of this error in SF:
` [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Do not use org.jsoup, see LPD-42623: ./modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/v5_6_1/DDMFieldAttributeUpgradeProcess.java (SourceCheck:IllegalImportsCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
`
I did a similar fix: https://github.com/brianchandotcom/liferay-portal/pull/157132/commits/2240c228ebbd28a97d2d7c685ac6be2f01d2f1f4

2024-12-27 19:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-12-27 19:33 UTC, vngoliveira commented
ci:test:sf

2024-12-27 19:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/6058/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/6058/jenkins-report.html">here</a>.</b></p>

2024-12-27 19:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b0b255f615829d1bd4b1a9ba9887588b9adc4571">b0b255f615829d1bd4b1a9ba9887588b9adc4571</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-45168">LPD-45168</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/b1669fec47c8352debf23070de004881a9c651e1">b1669fec47c8352debf23070de004881a9c651e1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/6058/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/6058/jenkins-report.html">here</a>.</h5></details></html>

2025-01-02 13:40 UTC, carolmariaabb requested changes

2025-01-02 15:34 UTC, vngoliveira commented
ci:test:sf

2025-01-02 15:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/7138/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/7138/jenkins-report.html">here</a>.</b></p>

2025-01-02 15:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2d939659c9fa4733606a13c38b6a0f103ede1734">2d939659c9fa4733606a13c38b6a0f103ede1734</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/vngoliveira/liferay-portal/tree/LPD-45168">LPD-45168</a><br/>Branch GIT ID: <a href="https://github.com/vngoliveira/liferay-portal/commit/c0ac1b4360e758485c582546b3233fedb32f6898">c0ac1b4360e758485c582546b3233fedb32f6898</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/7138/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/7138/jenkins-report.html">here</a>.</h5></details></html>

2025-01-02 15:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/7138/">test-portal-source-format#7138</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/7138/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/4018">liferay-bpm#4018</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/102307687">[master] ci:test:sf - vngoliveira &gt; liferay-bpm - PR#4018 - 2025-01-02[07:34:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>102307687<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/27242/">publish-testray-report#27242</a><br/></div></div>

2025-01-02 16:04 UTC, carolmariaabb approved these changes

2025-01-02 16:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/12039/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12039/jenkins-report.html">here</a>.</b></p>

2025-01-02 16:12 UTC, liferay-continuous-integration commented
ci:test:upgrade

Invoking upgrade test suite because an upgrade file has been modified.

2025-01-02 16:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>upgrade</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12523/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12523/jenkins-report.html">here</a>.</b></p>

2025-01-02 17:48 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 32 out of 33 jobs passed in 1 hour 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2d939659c9fa4733606a13c38b6a0f103ede1734">2d939659c9fa4733606a13c38b6a0f103ede1734</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2d939659c9fa4733606a13c38b6a0f103ede1734">2d939659c9fa4733606a13c38b6a0f103ede1734</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/102133444">EE Development Acceptance (master) - 1111 - 2025-01-01[12:37:30]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 31 out of 33 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/12039/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1044737/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/500314/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449104/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/500316/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/474334/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113227/">js-unit/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048382/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452985/">modules-compile/0/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/474335/">modules-compile/0/1</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458370/">modules-compile/0/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388700/">modules-compile/0/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/500315/">modules-compile/0/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/474333/">modules-compile/0/5</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452983/">modules-compile/0/6</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388698/">modules-compile/0/7</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/401445/">modules-compile/0/8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458369/">modules-compile/0/9</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449102/">modules-compile/0/10</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449103/">modules-compile/0/11</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388699/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003698/"><strike>modules-integration-mysql57/0/0</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/992529/">modules-integration-mysql57/0/1</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061499/">modules-integration-mysql57/0/2</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/992528/">modules-integration-mysql57/0/3</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061501/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-semantic-versioning<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1152526/">modules-semantic-versioning/0/0</a></li></ul></li><li>modules-unit<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/401444/">modules-unit/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452984/">modules-unit/0/1</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/458368/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/474332/">playwright-js-tomcat90-mysql57/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388697/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/452982/">unit_stable/0/0</a></li></ul></li></ul></div><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12039/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at 2d939659c9fa4733606a13c38b6a0f103ede1734:</strong></summary><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003698//consoleText">modules-integration-mysql57/0/0</a><ol><li><details><summary><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003698/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest">com.liferay.portal.log.assertor.PortalLogAssertorTest</a></summary><div><ol><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003698//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">testScanXMLLog</a></li></ol></div></details></li></ol></div></li></ol></details></details></html>

2025-01-02 18:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:upgrade - 303 out of 312 jobs passed in 1 hour 48 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2d939659c9fa4733606a13c38b6a0f103ede1734">2d939659c9fa4733606a13c38b6a0f103ede1734</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2d939659c9fa4733606a13c38b6a0f103ede1734">2d939659c9fa4733606a13c38b6a0f103ede1734</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/102133444">EE Development Acceptance (master) - 1111 - 2025-01-01[12:37:30]</a></p><details><summary><strong>ci:test:upgrade - 303 out of 312 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12523/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-db2111<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1285708/">functional-tomcat90-db2111/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983121/">functional-tomcat90-db2111/1/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1113301/">functional-tomcat90-db2111/1/1</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1285715/">functional-tomcat90-db2111/1/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1162179/">functional-tomcat90-db2111/1/3</a></li></ul></li><li>functional-tomcat90-mariadb102<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1285723/">functional-tomcat90-mariadb102/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/500349/">functional-tomcat90-mariadb102/1/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/449135/">functional-tomcat90-mariadb102/1/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1152605/">functional-tomcat90-mariadb102/1/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003683/">functional-tomcat90-mariadb102/1/3</a></li></ul></li><li>functional-tomcat90-mysql57<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738209/">functional-tomcat90-mysql57/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/992551/">functional-tomcat90-mysql57/0/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1255584/">functional-tomcat90-mysql57/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814104/">functional-tomcat90-mysql57/1/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738206/">functional-tomcat90-mysql57/1/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055228/">functional-tomcat90-mysql57/1/2</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003668/">functional-tomcat90-mysql57/1/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003666/">functional-tomcat90-mysql57/1/4</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1055227/">functional-tomcat90-mysql57/1/5</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003664/">functional-tomcat90-mysql57/1/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003665/">functional-tomcat90-mysql57/1/7</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003667/">functional-tomcat90-mysql57/1/8</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738204/">functional-tomcat90-mysql57/1/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1285711/">functional-tomcat90-mysql57/1/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1285709/">functional-tomcat90-mysql57/1/11</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453008/">functional-tomcat90-mysql57/1/12</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1285710/">functional-tomcat90-mysql57/1/13</a></li></ul></li><li>functional-tomcat90-mysql80<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1048461/">functional-tomcat90-mysql80/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814118/">functional-tomcat90-mysql80/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1044810/">functional-tomcat90-mysql80/0/2</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/401465/">functional-tomcat90-mysql80/1/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/453006/">functional-tomcat90-mysql80/1/1</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1255587/">functional-tomcat90-mysql80/1/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814111/">functional-tomcat90-mysql80/1/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1003672/">functional-tomcat90-mysql80/1/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1152594/">functional-tomcat90-mysql80/1/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983118/">functional-tomcat90-mysql80/1/6</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1044802/">functional-tomcat90-mysql80/1/7</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1061528/">functional-tomcat90-mysql80/1/8</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/474360/">functional-tomcat90-mysql80/1/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1255590/">functional-tomcat90-mysql80/1/10</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/814115/">functional-tomcat90-mysql80/1/11</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/983120/">functional-tomcat90-mysql80/1/12</a></li></ul></li><li>functional-tomcat90-oracle193<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1285716/">functional-tomcat90-oracle193/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-a [...]

2025-01-02 18:04 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/12523/">test-portal-acceptance-pullrequest(master)#12523</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12523/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>upgrade<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-bpm/liferay-portal/pull/4018">liferay-bpm#4018</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/102338420">[master] ci:test:upgrade - vngoliveira &gt; liferay-bpm - PR#4018 - 2025-01-02[08:12:19]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>102338420<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/27249/">publish-testray-report#27249</a><br/></div></div>

2025-01-02 18:21 UTC, carolmariaabb commented
ci:forward

2025-01-02 18:21 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2025-01-02 18:21 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2025-01-02 18:22 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/1795//consoleFull)

2025-01-02 18:22 UTC, closed without merging

2025-01-02 18:22 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/157419
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/1795//consoleFull)